### ISSUE TITLE
SuperUser Id pass not found 

### ISSUE THREAD

**Issue by iamsharad98** [celikyuksell/Django-E-Commerce#3]
You forgot to give super user id pass and when I try to create new super user, I managed to login but admin look like this when I click on anything it looks like this again and again and nothing opens

![Capture](https://user-images.githubusercontent.com/26202526/96675465-8f902280-1388-11eb-974e-7c490e180fbe.PNG)

**Comment by celikyuksell** [comment]
Thank you for your attention..
I added Super User name and password at Readme inf. page
Best
